config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'blogs/topic_search/:id', to: 'blogs#topic_search', as: 'topic_search'
  get 'blogs/topic/new', to: 'blogs#new_topic', as: 'new_topic'
  post 'blogs/topic/create', to: "blogs#create_topic", as: 'create_topic'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'nil', to: 'pages#nilpage'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates_presence_of :title, :body, :topic
  
  belongs_to :topic
  
  has_many :comments, dependent: :destroy
  
  after_initialize :set_defaults
  
  def set_defaults
    self.topic ||= Topic.last
  end
  
  def self.set_order
    order("updated_at DESC")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_topics
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_page_title, only: [:show, :edit, :update]
  access all: [:show, :index, :topic_search], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status, :new_topic , :create_topic]}, site_admin: :all
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.set_order.page(params[:page]).per(5)
    else
      @blogs = Blog.published.set_order.page(params[:page]).per(5)
    end
    @page_title = "#{@name} | Blogs"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    
    if ! logged_in?(:site_admin) && @blog.status == "draft"
      flash[:alert] = "You are not allowed to view that blog"
      redirect_to blogs_path
    end
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @page_title = "#{@name} | New Blog"
    @topics = Topic.all
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def new_topic
    @topic = Topic.new
    @page_title = "#{@name} | New Topic"
  end
  
  def create_topic
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to blogs_path, notice: 'Topic was successfully created.' }
      else
        flash[:alert] = "Title field must be filled"
        format.html { render :new_topic }
      end
    end
    
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def topic_search
    if logged_in?(:site_admin)
      @blogs = Topic.friendly.find(params[:id]).blogs.set_order.page(params[:page]).per(5)
    else
      @blogs = Topic.friendly.find(params[:id]).blogs.published.set_order.page(params[:page]).per(5)
    end
    puts @blogs
    render :index
  end


  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: "#{@blog.title}'s status has been changed to #{@blog.status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
    
    def set_page_title
      @page_title = "#{@name} | #{@blog.title}"
    end
    
    def topic_params
      params.require(:topic).permit(:title)
    end
    
    def set_topics
      @topics = Topic.includes(:blogs).where.not(blogs: {id: nil})
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
    
    def gravatr_helper user
       image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40 
    end
    
    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
           CodeRay.scan(code, language).div
        end
    end
    
    def markdown(text)
        coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
        
        options = {
            fenced_code_blocks: true,
            no_intra_emphasis: true,
            autolink: true,
            lax_html_blocks: true
        }
        
        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end
    
    def blog_status_color blog
        if blog.draft?
            return "color: orange;"
        else
            return "color: green;"
        end
    end
end

app/views/blogs/_admin_actions.html.erb
<span>
    <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %> | 
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %> | 
    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
</span>

app/views/blogs/_blog.html.erb
<% if blog.published? || logged_in?(:site_admin) %>
    <div class="blog-post">
        <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %>  </h2>
        <%= render partial: "blogs/admin_actions", locals: {blog: blog} if logged_in?(:site_admin)%>
        <p class="blog-post-meta"><%= "Published #{distance_of_time_in_words(blog.created_at, Time.now)} ago "%></p>
        
        <p>
            <%= blog.body %>
        </p>
    </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error, "Bad Input", 5000 %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :blog_title, class: "form-control", placeholder: 'Title' %>
  </div>
  
  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>
    <br />
    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Publish' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <% if @topics.each.count > 0 %>
      <%= form.collection_select(:topic_id, Topic.all, :id, :title, {selected: blog.topic.id, include_blank: true}, class: 'form-control') %>
    <% end %>
    <%= link_to "+ add topic", new_topic_path %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, id: :blog_body, class: "form-control", rows: 15, placeholder: 'content' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/_topic_links.html.erb
<% @topics.each do |topic| %>
    <%= link_to "#{topic.title}", topic_search_path(topic.slug), class: "text-white topic-block" %>
<% end %>
<hr class="text-white" />
<%= link_to "All Blogs", blogs_path, class: "text-white topic-block" %>
<%= link_to "New topic", new_topic_path, class: 'text-white topic-block' if logged_in?(:site_admin) %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
        
    <h1>Editing Blog</h1>
    
    <%= render 'form', blog: @blog %>
    
    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Create a new Blog', new_blog_path if logged_in?(:site_admin) %>
  <%= render @blogs %>
  
  <%= paginate @blogs %>

</div>
  

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
    
    <h1>New Blog</h1>
    
    <%= render 'form', blog: @blog %>
    
    <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/new_topic.html.erb
<div class="col-sm-8 blog-main">
    <%= form_for(@topic, url: create_topic_path) do |f| %>
      <% if @topic.errors.any? %>
        <% @topic.errors.full_messages.each do |error| %>
          <%= alert_generator error, "Bad Input", 5000 %>
        <% end %>
      <% end %>
      
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
        </div>
    
          <div class="form-group">
            <%= f.submit "Submit", class: "btn btn-success btn-block" %>
          </div>
      <% end %>
 </div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  
  <h2><%= @blog.title %></h2>
  
  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to "#{@blog.topic.title}", topic_search_path(@blog.topic.slug), class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>
    <span class="pull-right">
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
      <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: "Are you sure you want to delete blog \"#{@blog.title}\"" } %>
    </span>
  </nav>
  
  <div><%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %></div>
  <div class="text-right comment-attributes">Topic: <%= @blog.topic.title %></div>
  
  <p>
    <%= markdown @blog.body %>
  </p>
  
  <!--start comment form-->
  <%= render "comments/comment_form" %>
  <!--end comment form-->
  
  <!--start comments-->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

  <!--end comments-->
</div>