config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'blogs/topic_search/:id', to: 'blogs#topic_search', as: 'topic_search'
  get 'blogs/topic/new', to: 'blogs#new_topic', as: 'new_topic'
  post 'blogs/topic/create', to: "blogs#create_topic", as: 'create_topic'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'nil', to: 'pages#nilpage'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    
    has_many :technologies
    accepts_nested_attributes_for :technologies, allow_destroy: true, reject_if: lambda { |attrs| attrs['name'].blank?}
    
    validates_presence_of :title, :body
    
    mount_uploader :thumb_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader
    
    def self.capture(string:)
        where(subtitle: string)
    end
    
    scope :someting_awesome, -> {where(subtitle: "Something Awesome")}
    
    def self.by_position
       order("position ASC") 
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: [:edit, :update, :show, :destroy]
    before_action :set_page_title, only: [:edit, :update, :show]
    layout 'portfolio'
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
    
    def index
       @portfolio_items = Portfolio.by_position
       @page_title = "#{@name} | Portfolios"
    end
    
    def new
        @portfolio_item = Portfolio.new
        @page_title = "#{@name} | New Portfolio"
    end
    
    def create
        @portfolio_item = Portfolio.new(portfolio_params)
        
        puts("#############{@portfolio}##########")
        
        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_path, notice: "Portfolio \"#{@portfolio_item.title}\" was created" }
            else
                format.html {render :new }
            end
        end
    end
    
    def edit
        
    end
    
    def update
        
        respond_to do |format|
            if @portfolio_item.update(portfolio_params)
                format.html {redirect_to portfolios_path, notice: "The portfolio was updated!" }
            else
                format.html {render :edit }
            end
        end
    end
    
    def show
    end
    
    def destroy
       
       
       #destroy record
       @portfolio_item.destroy
       
       #redirect
       respond_to do |format|
           format.html {redirect_to portfolios_path, notice: "Portfolio was destroyed" }
           format.json { head :no_content }
       end
    end
    
    def sort
        params[:order].each do |key, value|
           Portfolio.find(value[:id]).update(position: value[:position]) 
        end
        
        head :ok
    end
    
    #These are methods for common code
    private
        def portfolio_params
            params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:id, :name, :_destroy])
        end
        
        def set_portfolio
           @portfolio_item = Portfolio.find(params[:id])
        end
        
        def set_page_title
           @page_title = "#{@name} | #{@portfolio_item.title}" 
        end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    
    def portfolio_img img, type
        if img.model.main_image? || img.model.thumb_image?
            img
        elsif type == 'thumb'
            image_generator(height:'350', width: '200')
        elsif type == 'main'
            image_generator(height:'600', width: '400')
        end
    end

   def image_generator(height:, width:)
      "https://placehold.it/#{height}x#{width}" 
   end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error, "Bad Input", 5000 %>
    <% end %>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control"%>
      </div>
      
    </div>
    <div class="col-md-6">
      <h4>Technologies</h4>
      <ul class= "form-group">
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        
        <li>
          <%= link_to_add_association "Add Technology", f, :technologies %>
        </li>
      </ul>
    </div>
  </div>
  
  <div class= "row text-center">
    <div class= "col-md-6">
      <div class="form-group text-center">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>
      
    </div>
    <div class="col-md-6">
        <div class="form-group text-center">
        <label class="btn btn-success portfolio-btn-custom">
          Upload a thumb image <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<% portfolio_item = portfolio %>
<hr>
<h3><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h3>
<%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?%>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
<%= link_to "Destroy Portfolio", portfolio_path(portfolio_item), method: :delete, data: {} %>

app/views/portfolios/_portfolio_item.html.erb
<div class="center-block">
    <div class="card" data-id="<%= portfolio_item.id %>">
        <p class="text-center">
            <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
        </p>
        <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%'%>
        <p class="card-text">
            <%= portfolio_item.subtitle %>
        </p>
    
        <% if logged_in?(:site_admin) %>
            <p class="card-text">
                <%= link_to "Edit", edit_portfolio_path(portfolio_item.id)%> | 
                <%= link_to "Destroy Portfolio", portfolio_path(portfolio_item), method: :delete, data: {}%>
            </p>
        <% end %>
    
    
    </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<li class="nested-fields">
    <div class="row">
        <div class="col-md-10">
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="col-md-2 btn btn-danger">
            <%= link_to_remove_association 'X', f %>
        </div>
    </div>
</li>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
    <h1>Edit this Portfolio</h1>
    
    <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<%= render 'shared/portfolio_mast' unless logged_in?(:site_admin) %>
<%= link_to "Create a new portfolio", new_portfolio_path if logged_in?(:site_admin) %>
<div class="album text-muted">
    <div class="container">
        <div class="row <%= 'sortable' if logged_in?(:site_admin)%>">
            
            <%= render partial: 'portfolio_item', collection: @portfolio_items %>
        </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
    <h1>Create a new Portfolio</h1>
    <%= render 'form', portfolio_item: @portfolio_item %> 
</div>

app/views/portfolios/show.html.erb
<div class="container text-center portfolio-form">
    <br />
    <br />
    <br />
  <div class="row">
    <div class="col-md-6">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
    </div>

    <div class="col-md-6 text-left">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>