config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'blogs/topic_search/:id', to: 'blogs#topic_search', as: 'topic_search'
  get 'blogs/topic/new', to: 'blogs#new_topic', as: 'new_topic'
  post 'blogs/topic/create', to: "blogs#create_topic", as: 'create_topic'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'nil', to: 'pages#nilpage'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/shared/_alert.html.erb
<% if flash[:alert] %>
    <%= js add_gritter(flash[:alert], :title => "Alert", :sticky => false, :time => 1000) %>
<% elsif flash[:notice] %>
    <%= js add_gritter(flash[:notice], :title => "Notice", :sticky => false, :time => 1000) %>
<% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], :title => "Error", :sticky => false, :time => 5000) %>
<% end %>

app/views/shared/_application_footer.html.erb
<div class="mastfoot app-footer">
    <div class="inner">
        <p><%= @copyright %></p>
        <%= source_helper("application") %>
    </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
<div class="inner">
  <h3 class="masthead-brand"><%= @name %></h3>
  <nav class="nav nav-masthead app-nav">
    <%= nav_helper 'span', 'nav-link' %>
    <%= login_helper 'nav-link'%>
  </nav>
</div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
   <%= @copyright %>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title"><%=@name%>'s Blog</h1>
    <p class="lead blog-description">A Blog page created by <%= @name %>.</p>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper "span", "nav-link" %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="pos-f-t dropdown-mar" >
    <div class="collapse rounded-top "  id="navbarToggleExternalContent" >
      <div class="bg-inverse p-4 rounded-top" >
      <!--  <h4 class="text-white">Search</h4> -->
      <!--  <span class="text-muted">Toggleable via the navbar brand.</span> -->
      <%= render 'topic_links' %>
      </div>
    </div>
    <nav class="navbar navbar-inverse bg-inverse rounded-bottom">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" >
        <span> >Topic search</span>
      </button>
    </nav>
  </div>
  <div>
    <%= source_helper('alert alert-info') %>
  </div>
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p><%= @blogabout.html_safe %></p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <div class="list-unstyled social-links">
      <a href=<%= @github %>><%= fa_icon "github-square" %></a>
      <a href=<%= @facebook %>><%= fa_icon "facebook-square" %></a>
      <a href=<%= @twitter %>><%= fa_icon "twitter-square" %></a>
      <a href=<%= @instagram %>><%= fa_icon "instagram" %></a>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "About", about_path %></div>
    <div><%= link_to "Blogs", blogs_path %></div>
    <div><%= link_to "Portfolios", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= "#{link_to "All Portfolios", portfolios_path}  | ".html_safe if request.env['PATH_INFO'] != portfolios_path %>
      <a href="#">Back to top</a>
    </p>
    <p><%= @copyright %>
  </div>
</footer>

app/views/shared/_portfolio_mast.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <p class = "notice"><%= notice %></p>
    <p class = "alert"><%= alert %></p>
    <h1 class="jumbotron-heading"><%= @name %>'s portfolio collection</h1>
    <p class="lead text-muted"><%= @portfolioAlbumCorrolation.html_safe %></p>
    <p>
      <%= link_to "Home", root_path, class: "btn btn-primary" %>
      <%= link_to "Blog", blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<!-- start of navbar -->
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted"><%= @portfolioAboutDrop.html_safe %></p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Navigation</h4>
        <ul class="list-unstyled">
          <%= login_helper 'text-white' %>
          <%= nav_helper "li", "text-white" %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand"><%= @name %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

<%= source_helper("text-muted text-center") %>
<!-- end of navbar -->